name: Python Flask Docker build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
   
    - name: Build Docker Image
      run: docker build -t dockerimage .
      
